### PR TITLE
fix(#3308): Declare AuthConfigurationServlet in hawtio-springboot

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by tadayosi** [comment]
Spring Boot E2E tests are still failing. We need to fix them before merging it.

**Comment by grgrzybek** [comment]
Looks like it's Selenium and I'd really appreciate any help here...

**Comment by tadayosi** [comment]
@jsolovjo Would you mind helping us on the E2E issue?

**Comment by grgrzybek** [comment]
can we run the tests locally and check what's the problem?

**Comment by tadayosi** [comment]
@grgrzybek It appears the tests projects don't build with the pull req. `mvn install -Pe2e`
Please look at this readme to see how you can build & run the E2E tests locally:
https://github.com/hawtio/hawtio/blob/4.x/tests/README.md

**Comment by grgrzybek** [comment]
I see problems like:
```
Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"div.pf-c-login"}
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:89)
	at com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:142)
	at com.codeborne.selenide.impl.WebElementSource.handleError(WebElementSource.java:141)
	at com.codeborne.selenide.impl.WebElementSource.checkConditionAndReturnElement(WebElementSource.java:125)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:102)
	at com.codeborne.selenide.commands.Should.execute(Should.java:30)
	at com.codeborne.selenide.commands.Should.execute(Should.java:14)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:162)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:132)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:84)
	at jdk.proxy2/jdk.proxy2.$Proxy31.shouldBe(Unknown Source)
	at io.hawt.tests.features.pageobjects.pages.LoginPage.login(LoginPage.java:30)
	at io.hawt.tests.features.setup.LoginLogout.login(LoginLogout.java:48)
...
```

isn't it related to Patternfly and CSS changes?

**Comment by tadayosi** [comment]
@grgrzybek Have you tried the following?
```
mvn install -Pe2e,fastinstall
mvn spring-boot:run -Pe2e -pl tests/springboot
```

**Comment by grgrzybek** [comment]
OK, I got it. I could run the e2e tests, saw Chrome (actually Chromium) run, I couldn't login. Checking the processes I could run the underlying SpringBoot based hawtio outside of e2e test and I could debug it and check it's simply missing 2932d55cc1c04bcd8356ad0cbe5d0bc4abf10739 commit.

Let me run the tests and pr check again.

**Comment by grgrzybek** [comment]
OK it worked - thanks @jsolovjo and @tadayosi for help!

**Comment by tadayosi** [comment]
thanks!

**Pull request merged**
