### PR TITLE
Updated keycloak type definitions

### PR DESCRIPTION
**Pull request by klinki**
Updated KeyCloak type definitions based on manual: https://keycloak.gitbooks.io/securing-client-applications-guide/content/topics/oidc/javascript-adapter.html

### CODE REVIEW

**Comment by klinki** [comment]
This might be related to TypeScript version. Which version do you use?

**Comment by davsclaus** [comment]
Yeah hawtio v1 uses an older TS version. @gashcrumb do you remember?

**Comment by gashcrumb** [comment]
Yeah, it's an ancient version, this is on grunt-typescript 0.4.0 which is typescript 1.1.0-1, so definitely need to stick with typescript 1.x compatible definitions.

**Comment by davsclaus** [comment]
[merge]

**Comment by davsclaus** [comment]
Thanks it compiles now

**Pull request merged**
