### PR TITLE
chore(console-assembly): update dependencies

### PR DESCRIPTION
**Pull request by GChuf**
Updates node (v10 -> v14) and yarn versions (v1.19 -> v1.22) and removed installation of npm (when downloaded through maven build)
Updates other dev dependencies
Speeds up build times (from 75s to 50s on my machine)
Gulp build process needed some editing due to node + gulp update

Let me know if anything needs changing before/if this gets merged

### CODE REVIEW

**Comment by tadayosi** [comment]
The changes look good, but the build&test CI doesn't pass. Can you see why it fails?

**Review by tadayosi — APPROVED** [review]
Looks good. Let's merge this and see what happens.

**Comment by tadayosi** [comment]
Thank you!

**Comment by GChuf** [comment]
@tadayosi it seems github build times aren't so different after this commit.
Maybe it would make sense to include node_modules folder in cache, like you do for maven (.m2/repository).
It would save ~20seconds and downloading node dependencies on each commit.

**Pull request merged**
