### PR TITLE
feat: update @hawtio/react to 1.3.0-dev.1

### PR DESCRIPTION
**Pull request by mmelko**

### CODE REVIEW

**Review by tadayosi — CHANGES_REQUESTED** [review]
You need to run `mvn clean install` locally and also add the updates to `yarn.lock`.

**Comment by tadayosi** [comment]
@mmelko Also the commit message should be `fix:` instead of `feat:` as the upgrade won't bring any new features.

**Comment by mmelko** [comment]
Thanks! I haven't realised that.  Of course you're right. I added the .lock files too.

**Review by tadayosi — COMMENTED** [review]
sorry, one more request. please update sample-plugin as well.

**Comment by mmelko** [comment]
> sorry, one more request. please update sample-plugin as well.

https://github.com/hawtio/hawtio/pull/3520/files#diff-136042127dd821d7751754d25dbf4d780b795fb5936b3393b77d1e1f74d2dfe3 it is

**Review by tadayosi — APPROVED** [review]

**Pull request merged**
