### PR TITLE
fix(#3178): Treat /proxy as /jolokia path and do not redirect to /aut…

### PR DESCRIPTION
**Pull request by grgrzybek**
…h/login

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by grgrzybek** [comment]
@tadayosi please decide whether to merge it. IMO, `/jolokia` and `/proxy` should be treated equally by `io.hawt.web.auth.LoginRedirectFilter` - this is how it worked with Hawtio 1.

**Comment by tadayosi** [comment]
Note `ProxyServlet` can be easily a target for security attacks such as CSRF, so we'd need to be careful to make it public.

**Comment by grgrzybek** [comment]
> Note `ProxyServlet` can be easily a target for security attacks such as CSRF, so we'd need to be careful to make it public.

Good point and actually a clarification of our discussion.

Let me summarize the discussion here:
* there's _main_ Hawtio tab and _connect_ tabs (for remote Jolokia agents accessed via proxy).
* for _connect_ tabs, `/proxy` requests are being sent with `Authorization` header specific to remote Jolokia, not to Hawtio itself (that's why `io.hawt.web.auth.LoginRedirectFilter#tryAuthenticateRequest()` from 243393102a44c01bd7eb97d31875b43cb45c484a should NOT be called for proxied requests)

We were wondering whether logging out (explicitly or by session timeout) from _main_ Hawtio tab should lead to logout of all _connect_ tabs.
* without this PR, after _main_ tab logs out, _connect_ tabs keep sending `/proxy` requests and are redirected to `/auth/login` AND also the credentials for remote Jolokia are used for Hawtio login (which is wrong). This leads to hawtio/hawtio-next#705 - "Connection lost. Retrying..." is being shown. The point is that it's a connection to proxy servlet, not to the remote agent. That's why I added `/proxy` to the list here.

However, if we explicitly admit that _`ProxyServlet` can be easily a target for security attacks such as CSRF, so we'd need to be careful to make it public_, we should rather put `/proxy` together with `/jolokia` under the mapping for `AuthenticationFilter`... This will cause 403 from AuthenticationFilter before 302 from LoginRedirectFilter... Let me check this.

**Comment by tadayosi** [comment]
Thinking about it a bit further, now I'm not sure if this change is really the right direction. The change is intended to expose an originally protected endpoint for an edge case hawtio/hawtio-next#705, but it also means it exposes the endpoint in the normal cases, which has been secure, and anyone can access it. In terms of impact, this will open an unnecessary hole in the majority of normal cases in order to support a rare case.

If we really need to expose the proxy, we might as well need to add some other way to maintain the same level of security in the normal cases.

**Comment by grgrzybek** [comment]
Seeing all the risks, I'd conclude with a statement:

> Hawtio's ProxyServlet is a feature that should be protected.

More precisely:
* even if the remote Jolokia agent doesn't maintain session, session timeout or explicit logout from Hawtio should forbid user from using Hawtio's proxy servlet and _connect_ tab should be logged out too
* we can't simply map `/proxy/*` to AuthenticationFilter, because we actually can't authenticated the user - because `Authorization` header is provided for remote Jolokia, not for us (Hawtio)
* LoginRedirectFilter should NOT redirect unauthenticated `/proxy/*` request to `/auth/login`. 403 should be returned instead (but by different filter or ProxyServlet itself) - this will ensure that _connect_ tab is logged out.

**Comment by grgrzybek** [comment]
Of course it's more complicated with Keycloak/OIDC, because there's no "subject" session attribute set by LoginServlet...

**Comment by grgrzybek** [comment]
Closing this PR, as this needs to be solved differently (see: #3178, #3371, #3379)

**Pull request closed without merging**
