### PR TITLE
Plugin proposal: Diagnostics: DiagnosticCommand + HotSpotDiagnostic

### PR DESCRIPTION
**Pull request by skarsaune**
Diagnostic plugin
 * Flight recorder - control jfr from hawtio
 * Class Histogram - obtain and parse class histogram + calculate diff from previous run
 * JVM flags - Show and edit JVM diagnostic flags

image
image
image

### CODE REVIEW

**Comment by skarsaune** [comment]
Improvement suggestions are of course welcome

**Comment by tadayosi** [comment]
Thanks @skarsaune for your contribution!  It looks awesome.

@davsclaus What do you think with this?  Do you think it's fine to merge this pull?

**Comment by oscerd** [comment]
Looks great

**Comment by davsclaus** [comment]
+1

**Comment by tadayosi** [comment]
OK, let's merge it. Thanks @skarsaune for your contribution!

**Pull request merged**
