### PR TITLE
[E2E Tests] Refactor tests according to Patternfly 5 changes

### PR DESCRIPTION
**Pull request by jsolovjo**
- Refactor tests (fix) according to Patternfly 5 changes in https://github.com/hawtio/hawtio-next/pull/953

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]

**Comment by jsolovjo** [comment]
Just noticed that the Login pages use different class names with and without v5

When opening a pure Hawtio, it uses div.pf-v5-c-login and when opening Hawtio with a running app (e.g. Quarkus), the Login page has div.pf-c-login

Screenshot 2024-05-30 at 15 19 46
Screenshot 2024-05-30 at 15 20 34

**Comment by tadayosi** [comment]
@jsolovjo Note I committed https://github.com/hawtio/hawtio/pull/3459/commits/a59e7bba5b022af703a0b615c81af59c9122c87b on top of your branch to make it run with the latest hawtio-react. If you overwrite it, hawtio-react will be rolled back to the older one.

**Comment by tadayosi** [comment]
Now it fails with different errors:
```
Error:  Failures: 
Error:  Checking the functionality of Camel Routes page..Check that Camel Source is not empty
Error:    Run 1: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133250670.3.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133250670.3.html
Timeout: 20 s.
Error:    Run 2: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133449125.10.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133449125.10.html
Timeout: 20 s.
Error:    Run 3: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133580019.16.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133580019.16.html
Timeout: 20 s.
Error:    Run 4: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133711154.22.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133711154.22.html
Timeout: 20 s.
[INFO] 
Error:  Checking the functionality of Camel Specific Route page..Check that Camel Source is not empty
Error:    Run 1: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133297232.4.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133297232.4.html
Timeout: 20 s.
Error:    Run 2: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133427419.9.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133427419.9.html
Timeout: 20 s.
Error:    Run 3: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133558332.15.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133558332.15.html
Timeout: 20 s.
Error:    Run 4: List size mismatch: expected: >= 1, actual: 0, collection: .view-line span
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133689451.21.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133689451.21.html
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133645791.19.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //td[text()='Hello Test']/preceding-sibling::td//button
[INFO] 
Error:  Checking the functionality of a Camel Specific Endpoint page..Check forwarding the message
Error:    Run 1: Element not found {By.xpath: //td[text()='Hello Test']/preceding-sibling::td//input}
Expected: enabled
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133167898.1.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133167898.1.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //td[text()='Hello Test']/preceding-sibling::td//input
Error:    Run 2: Element not found {By.xpath: //td[text()='Hello Test']/preceding-sibling::td//input}
Expected: enabled
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133405665.8.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133405665.8.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //td[text()='Hello Test']/preceding-sibling::td//input
Error:    Run 3: Element not found {By.xpath: //td[text()='Hello Test']/preceding-sibling::td//input}
Expected: enabled
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/171713353[6520](https://github.com/hawtio/hawtio/actions/runs/9313285063/job/25635619623?pr=3459#step:5:6521).14.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133536520.14.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //td[text()='Hello Test']/preceding-sibling::td//input
Error:    Run 4: Element not found {By.xpath: //td[text()='Hello Test']/preceding-sibling::td//input}
Expected: enabled
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133667507.20.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133667507.20.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //td[text()='Hello Test']/preceding-sibling::td//input
[INFO] 
Error:  Checking the functionality of a Camel Specific Endpoint page..Check sending a message
Error:    Run 1: Element not found {By.xpath: //textarea}
Expected: exist
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133146009.0.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133146009.0.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //textarea
Error:    Run 2: Element not found {By.xpath: //textarea}
Expected: exist
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133361753.6.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133361753.6.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //textarea
Error:    Run 3: Element not found {By.xpath: //textarea}
Expected: exist
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133492638.12.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133492638.12.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //textarea
Error:    Run 4: Element not found {By.xpath: //textarea}
Expected: exist
Screenshot: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133623666.18.png
Page source: file:/hawtio-test-suite/tests/hawtio-test-suite/build/reports/tests/1717133623666.18.html
Timeout: 20 s.
Caused by: NoSuchElementException: Unable to locate element: //textarea
```

**Comment by jsolovjo** [comment]
I fixed one issue on Sample Plugin page - the tests were relying on wrong (old) class name
However, there are some issues not related to the tests
Screenshot 2024-06-06 at 12 45 46
Screenshot 2024-06-06 at 12 55 53

**Comment by jsolovjo** [comment]
It seems it's failing because of https://github.com/hawtio/hawtio-next/issues/969
Discussed and identified it with Matej

**Pull request merged**
