### PR TITLE
#2294 Add whitelist regex support

### PR DESCRIPTION
**Pull request by fabienrousseau**

### CODE REVIEW

**Comment by tadayosi** [comment]
The whitelist is frequently checked when the proxy is used, so I agree that the `Pattern` object should be cached. I think `ProxyWhitelist` should have the cache. What about adding `protected List<Pattern> regexWhitelist` to `ProxyWhitelist` and adding another method `isAllowed(List<Pattern> regexWhitelist)` to `ProxyDetails`?  `regexWhitelist` should be read-only so I guess there's no need to use a thread-safe collection.

**Comment by tadayosi** [comment]
Please also don't forget to update https://github.com/hawtio/hawtio/blob/master/CHANGES.md. This enhancement is worth noting there.

**Comment by fabienrousseau** [comment]
I agree that `ProxyWhiteList` should have the cache. I will also add the `isAllowed` method to `ProxyDetails` (I tend to avoid doing so in general because it adds code in `ProxyDetails` class, and this code should probably reside in `ProxyWhiteList` only).

Good catch for the CHANGES.md file.

I think I can do the changes by the end of this week.

**Comment by tadayosi** [comment]
Thanks!

**Comment by fabienrousseau** [comment]
Thanks for this awesome tool and your reactivity.

**Pull request merged**
