### PR TITLE
[E2E Tests] New Camel Contexts Operations and Chart test scenarios

### PR DESCRIPTION
**Pull request by jsolovjo**
### In this PR:

New test scenarios for Camel Context covering:
- Camel Chart
  - View Chart
  - Edit Chart

- Camel Operatios
  - Execute the operation returning a result of `boolean` type
  - Execute the operation returning a result of `int` type

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]
LGTM, but the tests are failing. Please check them.

**Comment by jsolovjo** [comment]
> Details

Thanks. I will check it. Locally, it worked fine - I will investigate what went wrong.

**Comment by tadayosi** [comment]
We released 3.0 Beta1 already, so please rebase it first.

**Comment by jsolovjo** [comment]
Hi @tadayosi 
I will rebase it and I am thinking about to remove one test scenario as it it quite flaky - to get the value of the chart you have to hover over the specific chart bar. The thing is it's even buggy when checking it manually - quite often it doesn't show up from the first hover and it refreshes every a few seconds, to it loses the focus. I will try a few more attempts and if no success, I will leave a test checking that there are actually chart bars.

**Comment by tadayosi** [comment]
> The thing is it's even buggy when checking it manually - quite often it doesn't show up from the first hover and it refreshes every few seconds, so it loses the focus. I will try a few more attempts and if no success, I will leave a test checking that there are actually chart bars.

Yes, as the nature of the Chart view it refreshes frequently. The test should use a different approach than other views and might need to relax some checking. If possible, we can just check that the view constantly refreshes with different data.

**Review by tadayosi — APPROVED** [review]
Great job!  Thank you!

**Pull request merged**
