### PR TITLE
[E2E Tests] Camel Context and Component tests

### PR DESCRIPTION
**Pull request by jsolovjo**
This PR includes sample tests for Camel Context and Components, and also includes page objects with fragments and step definitions which will used by other tests in upcoming PRs.

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]
LGTM. Thanks!

**Review by Croway — COMMENTED** [review]
all of this is executed on each PR? how much time is needed for the execution?

**Comment by jsolovjo** [comment]
> all of this is executed on each PR? how much time is needed for the execution?

Regarding the logs on github

`
[INFO]  T E S T S
[2559](https://github.com/hawtio/hawtio/actions/runs/4175964700/jobs/7231617644#step:4:2560)
[INFO] -------------------------------------------------------
[2560](https://github.com/hawtio/hawtio/actions/runs/4175964700/jobs/7231617644#step:4:2561)
[INFO] Running io.hawt.tests.spring.boot.runners.RunSpringBootAllTest
[2561](https://github.com/hawtio/hawtio/actions/runs/4175964700/jobs/7231617644#step:4:2562)
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 105.532 s - in io.hawt.tests.spring.boot.runners.RunSpringBootAllTest
[2562](https://github.com/hawtio/hawtio/actions/runs/4175964700/jobs/7231617644#step:4:2563)
[INFO] 
[2563](https://github.com/hawtio/hawtio/actions/runs/4175964700/jobs/7231617644#step:4:2564)
[INFO] Results:
[2564](https://github.com/hawtio/hawtio/actions/runs/4175964700/jobs/7231617644#step:4:2565)
[INFO] 
[2565](https://github.com/hawtio/hawtio/actions/runs/4175964700/jobs/7231617644#step:4:2566)
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0
`

**Review by Croway — APPROVED** [review]
LGTM then!

**Pull request merged**
