### PR TITLE
Fixed #2556 Properties in AuthenticationConfiguration parsed wrong

### LINKED ISSUE #2556: Properties in AuthenticationConfiguration parsed wrong
io.hawt.web.auth.AuthenticationConfiguration

in the constructor there is:
// JVM system properties can override always
if (System.getProperty(HAWTIO_AUTHENTICATION_ENABLED) != null) {
    this.enabled = Boolean.getBoolean(HAWTIO_AUTHENTICATION_ENABLED);
}
if (System.getProperty(HAWTIO_NO_CREDENTIALS_401) != null) {
    this.noCredentials401 = Boolean.getBoolean(HAWTIO_NO_CREDENTIALS_401);
}

and further down:
if (System.getProperty(HAWTIO_KEYCLOAK_ENABLED) != null) {
    this.keycloakEnabled = this.enabled && Boolean.getBoolean(HAWTIO_KEYCLOAK_ENABLED);
}

but the values in those constants are:
HAWTIO_AUTHENTICATION_ENABLED = "hawtio." + AUTHENTICATION_ENABLED;
HAWTIO_NO_CREDENTIALS_401 = "hawtio." + NO_CREDENTIALS_401;
HAWTIO_KEYCLOAK_ENABLED = "hawtio." + KEYCLOAK_ENABLED

which will always parse to false.

this should clearly be changed to:
// JVM system properties can override always
if (System.getProperty(HAWTIO_AUTHENTICATION_ENABLED) != null) {
    this.enabled = Boolean.getBoolean(System.getProperty(HAWTIO_AUTHENTICATION_ENABLED));
}
if (System.getProperty(HAWTIO_NO_CREDENTIALS_401) != null) {
    this.noCredentials401 = Boolean.getBoolean(System.getProperty(HAWTIO_NO_CREDENTIALS_401));
}

if (System.getProperty(HAWTIO_KEYCLOAK_ENABLED) != null) {
    this.keycloakEnabled = this.enabled && Boolean.getBoolean(System.getProperty(HAWTIO_KEYCLOAK_ENABLED));
}

### PR DESCRIPTION
**Pull request by adamarmistead**
Fixed attempt to parse Boolean values from a system property key, not the value of the system property.

### CODE REVIEW

**Comment by tadayosi** [comment]
See javadoc for `Boolean.getBoolean()`. This is the correct usage.

**Comment by tadayosi** [comment]
Thank you for your efforts anyway.

**Comment by adamarmistead** [comment]
riiiight, you mean this doc? https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#parseBoolean(java.lang.String)

which literally says you have to pass the parseBoolean method a case insensitive string  of "true" or it will return false?

public static boolean parseBoolean(String s)

Parses the string argument as a boolean. The boolean returned represents the value true if the string argument is not null and is equal, ignoring case, to the string "true".

Example: Boolean.parseBoolean("True") returns true.
Example: Boolean.parseBoolean("yes") returns false.

Parameters:
    s - the String containing the boolean representation to be parsed
Returns:
    the boolean represented by the string argument
Since:
    1.5


And then your code calls it like this:
this.enabled = Boolean.getBoolean("hawtio.authenticationEnabled");
this.noCredentials401 = Boolean.getBoolean("hawtio.noCredentials401");
this.keycloakEnabled = this.enabled && Boolean.getBoolean("hawtio.keycloakEnabled");

which will result in this.enabled, this.noCredentials401, and this.keycloakEnabled always being false?
I'm positive that's wrong.

**Comment by tadayosi** [comment]
No, this one: https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#getBoolean(java.lang.String)

Have you actually configured those properties and confirmed they really don't work?

**Comment by adamarmistead** [comment]
HA! getBoolean, not parseBoolean DOH!
you win, sorry about that. :)

**Pull request closed without merging**
